name: CI
on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
  APPLICATION_NAME: waifu2x-ncnn-vulkan

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      APPNAME: ${{ steps.get_appname.outputs.APPNAME }}
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - name: get-appname
      id: get_appname
      run: echo ::set-output name=APPNAME::${APPLICATION_NAME}
    - name: get-version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

  ubuntu:
    needs: [setup]
    runs-on: ubuntu-20.04
    env:
      PACKAGENAME: waifu2x_vulkan_ubuntu_x86_64
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build
      run: |
        pip3 install wheel
        python3 setup.py bdist_wheel
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: dist
        retention-days: 7

  macos:
    runs-on: macos-latest
    env:
      PACKAGENAME: waifu2x_vulkan_macos_x86_64
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build
      run: |
        pip3 install wheel
        python3 setup.py bdist_wheel
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: dist
        retention-days: 7
