name: CI
on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
  APPLICATION_NAME: waifu2x-ncnn-vulkan

jobs:
  macos:
    runs-on: macos-13
    env:
      PACKAGENAME: waifu2x_vulkan_macos_x86_64
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
