name: CI
on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
  APPLICATION_NAME: waifu2x-ncnn-vulkan

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      APPNAME: ${{ steps.get_appname.outputs.APPNAME }}
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - name: get-appname
      id: get_appname
      run: echo ::set-output name=APPNAME::${APPLICATION_NAME}
    - name: get-version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

  ubuntu:
    needs: [setup]
    runs-on: ubuntu-20.04
    env:
      PACKAGENAME: waifu2x_vulkan_ubuntu_x86_64
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build
      run: |
        mkdir -p ${{ env.PACKAGENAME }}
        wget https://github.com/tonquer/waifu2x-vulkan/releases/download/v1.1.6/sr-ncnn-vulkan-1.2.0.tar.gz
        tar -zxvf sr-ncnn-vulkan-1.2.0.tar.gz
        cd sr-ncnn-vulkan-1.2.0
        pip3 install wheel
        python3 setup.py bdist_wheel
        cd ..
        cp -r sr-ncnn-vulkan-1.2.0/dist/* ${{ env.PACKAGENAME }}
        zip -9 -r ${{ env.PACKAGENAME }}.zip ${{ env.PACKAGENAME }}
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}
        retention-days: 7

  macos:
    runs-on: macos-13
    env:
      PACKAGENAME: waifu2x_vulkan_macos_x86_64
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build
      run: |
        mkdir -p ${{ env.PACKAGENAME }}
        wget https://github.com/tonquer/waifu2x-vulkan/releases/download/v1.1.6/sr-ncnn-vulkan-1.2.0.tar.gz
        tar -zxvf sr-ncnn-vulkan-1.2.0.tar.gz
        cd sr-ncnn-vulkan-1.2.0
        pip3.7 install wheel setuptools
        echo -e '#!/bin/bash\n/usr/bin/clang++ -std=c++11 $*' > /usr/local/bin/clang++
        echo -e '#!/bin/bash\n/usr/bin/gcc -std=c++11 $*' > /usr/local/bin/gcc
        chmod +x /usr/local/bin/clang++
        chmod +x /usr/local/bin/gcc
        python3.7 setup.py bdist_wheel
        cd ..
        cp -r sr-ncnn-vulkan-1.2.0/dist/* ${{ env.PACKAGENAME }}
        zip -9 -r ${{ env.PACKAGENAME }}.zip ${{ env.PACKAGENAME }}
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}
        retention-days: 7
